In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV,KFold
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import mean_squared_error

In [8]:
data=pd.read_csv("C:\\Users\\Dedshan Vimukthi\\Documents\\Dataset3\\Boston.CSV")

In [9]:
data.head()

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [11]:
x=data.iloc[:,:12]
y=data.iloc[:,12]

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [13]:
model=LinearRegression()
model.fit(x_train,y_train)
model.coef_

array([-1.25156811e-01,  4.48575121e-02,  2.01265385e-02, -1.62895522e+01,
        3.77366409e+00, -2.13185120e-03, -1.40611846e+00,  2.66835482e-01,
       -1.21692284e-02, -1.07660161e+00,  8.72533635e-03, -4.94425348e-01])

In [14]:
rmodel=Ridge(alpha=1)
rmodel.fit(x_train,y_train)
rmodel.coef_

array([-0.12233832,  0.04609301, -0.0098171 , -8.64343893,  3.81854443,
       -0.00952306, -1.29823342,  0.24385986, -0.01267859, -0.99836523,
        0.00913742, -0.50051639])

In [15]:
lmodel=Lasso(alpha=1)
lmodel.fit(x_train,y_train)
lmodel.coef_

array([-0.05889028,  0.05317657, -0.        , -0.        ,  0.67954962,
        0.01684077, -0.6487664 ,  0.198738  , -0.01399421, -0.86421958,
        0.00660309, -0.73120957])

In [16]:
emodel=ElasticNet(alpha=1)
emodel.fit(x_train,y_train)
emodel.coef_

array([-0.07922321,  0.05637835, -0.02484651, -0.        ,  0.84270351,
        0.01551814, -0.75788431,  0.22869565, -0.01471232, -0.85689217,
        0.00690502, -0.71471227])

In [17]:
y_pred=model.predict(x_test)
y_predr=model.predict(x_test)
y_predl=model.predict(x_test)
y_prede=model.predict(x_test)

In [19]:
print(mean_squared_error(y_pred,y_test))
print(mean_squared_error(y_predr,y_test))
print(mean_squared_error(y_predl,y_test))
print(mean_squared_error(y_prede,y_test))

34.21225254753325
34.21225254753325
34.21225254753325
34.21225254753325


In [2]:
data=pd.read_csv("C:\\Users\\Dedshan Vimukthi\\Documents\\Dataset3\\Boston.CSV")

In [3]:
data.head()

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [5]:
x=data.iloc[:,:12]
y=data.iloc[:,12]

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [7]:
model=Lasso()
params={"alpha":[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0]}
cval=KFold(n_splits=10)

In [8]:
gsearch=GridSearchCV(model,params,cv=cval)

In [9]:
result_grid=gsearch.fit(x_train,y_train)

In [10]:
result_grid.best_params_

{'alpha': 0.1}

In [11]:
lmodel=Lasso(alpha=0.1)
lmodel.fit(x_train,y_train)

Lasso(alpha=0.1)

In [12]:
lmodel.coef_

array([-0.11328068,  0.04781981, -0.03820164, -0.        ,  3.61884406,
       -0.01418714, -1.11799589,  0.21463545, -0.01329635, -0.90308334,
        0.00934528, -0.52609513])

In [13]:
model=Lasso()
params={"alpha":[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0]}
cval=KFold(n_splits=10)

In [16]:
rsearch=RandomizedSearchCV(model,params,cv=cval)
result_random=rsearch.fit(x_train,y_train)
result_random.best_params_

{'alpha': 0.1}