In [101]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.multioutput import MultiOutputRegressor

In [2]:
X=np.array([[1,0],[1,1],[1,2],[1,3],[1,4]])
Y=np.array([1,4,3,8,9]).reshape(5,1)

In [3]:
X

array([[1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4]])

In [4]:
Y

array([[1],
       [4],
       [3],
       [8],
       [9]])

In [5]:
XTX_inv=np.linalg.inv(X.T.dot(X))

In [7]:
XTY=X.T.dot(Y)

In [8]:
XTX_inv

array([[ 0.6, -0.2],
       [-0.2,  0.1]])

In [9]:
XTY

array([[25],
       [70]])

In [10]:
Beta_Hat=XTX_inv.dot(XTY)
Beta_Hat

array([[1.],
       [2.]])

In [13]:
Y_Hat=X.dot(Beta_Hat)

In [14]:
Y_Hat

array([[1.],
       [3.],
       [5.],
       [7.],
       [9.]])

In [15]:
Res_Hat=Y-Y_Hat

In [16]:
Res_Hat

array([[-2.22044605e-15],
       [ 1.00000000e+00],
       [-2.00000000e+00],
       [ 1.00000000e+00],
       [-1.77635684e-15]])

In [17]:
RSS=Res_Hat.T.dot(Res_Hat)
RSS

array([[6.]])

In [20]:
X=np.array([0,1,2,3,4]).reshape(5,1)
Y=np.array([1,4,3,8,9])

In [21]:
model=LinearRegression()

In [22]:
model.fit(X,Y)

LinearRegression()

In [23]:
model.coef_

array([2.])

In [24]:
model.intercept_

0.9999999999999991

In [25]:
X=np.array([[1,0],[1,1],[1,2],[1,3],[1,4]])
Y=np.array([[1,-1],[4,-1],[3,2],[8,3],[9,2]])

In [26]:
X

array([[1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4]])

In [27]:
Y

array([[ 1, -1],
       [ 4, -1],
       [ 3,  2],
       [ 8,  3],
       [ 9,  2]])

In [28]:
XTX_inv=np.linalg.inv(X.T.dot(X))

In [29]:
XTY=X.T.dot(Y)

In [30]:
XTX_inv

array([[ 0.6, -0.2],
       [-0.2,  0.1]])

In [31]:
XTY

array([[25,  5],
       [70, 20]])

In [32]:
Beta_Hat=XTX_inv.dot(XTY)
Beta_Hat

array([[ 1., -1.],
       [ 2.,  1.]])

In [33]:
Y_Hat=X.dot(Beta_Hat)

In [34]:
Y_Hat

array([[ 1.00000000e+00, -1.00000000e+00],
       [ 3.00000000e+00,  2.22044605e-16],
       [ 5.00000000e+00,  1.00000000e+00],
       [ 7.00000000e+00,  2.00000000e+00],
       [ 9.00000000e+00,  3.00000000e+00]])

In [35]:
Res_Hat=Y-Y_Hat

In [36]:
Res_Hat

array([[-8.88178420e-16, -2.22044605e-16],
       [ 1.00000000e+00, -1.00000000e+00],
       [-2.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00],
       [-3.55271368e-15, -1.00000000e+00]])

In [37]:
RSS=Res_Hat.T.dot(Res_Hat)
RSS

array([[ 6., -2.],
       [-2.,  4.]])

In [81]:
data=pd.read_csv("C:\\Users\\Dedshan Vimukthi\\Documents\\Dataset2\\dataX.CSV")

In [82]:
data

x1  x2  x3   y1   y2
0    2   3   2  1.0  3.0
1   -1  -1   2  1.0  2.0
2   -2   0   3  2.0  4.0
3    4   1   1  2.0  1.0
4    1   1   2  3.0  5.0
5    4   2   4  4.0  6.0
6    5   3   5  1.0  3.0
7    3   1   5  4.0  7.0
8    2   2  -2  5.0  8.0
9    3   7   6  2.0  2.0
10   2   3   2  NaN  NaN
11   1   2   3  NaN  NaN
12   1   4   2  NaN  NaN

In [83]:
data1=data.iloc[:10,:]
data2=data.iloc[10:,:]

In [84]:
data1

x1  x2  x3   y1   y2
0   2   3   2  1.0  3.0
1  -1  -1   2  1.0  2.0
2  -2   0   3  2.0  4.0
3   4   1   1  2.0  1.0
4   1   1   2  3.0  5.0
5   4   2   4  4.0  6.0
6   5   3   5  1.0  3.0
7   3   1   5  4.0  7.0
8   2   2  -2  5.0  8.0
9   3   7   6  2.0  2.0

In [85]:
data2["x0"]=1
data2

<ipython-input-85-86a372bc714c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["x0"]=1


x1  x2  x3  y1  y2  x0
10   2   3   2 NaN NaN   1
11   1   2   3 NaN NaN   1
12   1   4   2 NaN NaN   1

In [86]:
data1["x0"]=1

<ipython-input-86-f5e1a486b815>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1["x0"]=1


In [87]:
data1

x1  x2  x3   y1   y2  x0
0   2   3   2  1.0  3.0   1
1  -1  -1   2  1.0  2.0   1
2  -2   0   3  2.0  4.0   1
3   4   1   1  2.0  1.0   1
4   1   1   2  3.0  5.0   1
5   4   2   4  4.0  6.0   1
6   5   3   5  1.0  3.0   1
7   3   1   5  4.0  7.0   1
8   2   2  -2  5.0  8.0   1
9   3   7   6  2.0  2.0   1

In [88]:
x=data1[["x0","x1","x2","x3"]].values
y=data1[["y1","y2"]].values

In [89]:
x

array([[ 1,  2,  3,  2],
       [ 1, -1, -1,  2],
       [ 1, -2,  0,  3],
       [ 1,  4,  1,  1],
       [ 1,  1,  1,  2],
       [ 1,  4,  2,  4],
       [ 1,  5,  3,  5],
       [ 1,  3,  1,  5],
       [ 1,  2,  2, -2],
       [ 1,  3,  7,  6]], dtype=int64)

In [90]:
XTX_inv=np.linalg.inv(x.T.dot(x))

In [91]:
XTY=x.T.dot(y)

In [92]:
XTX_inv

array([[ 0.30385962, -0.02960391, -0.00726945, -0.04567124],
       [-0.02960391,  0.03095757, -0.01577306, -0.0019422 ],
       [-0.00726945, -0.01577306,  0.03661118, -0.01041728],
       [-0.04567124, -0.0019422 , -0.01041728,  0.02483668]])

In [93]:
XTY

array([[ 25.,  41.],
       [ 57.,  87.],
       [ 46.,  71.],
       [ 61., 103.]])

In [94]:
Beta_Hat=XTX_inv.dot(XTY)
Beta_Hat

array([[ 2.78872772,  4.66243626],
       [ 0.18044847,  0.15961391],
       [-0.03214001, -0.14388901],
       [-0.21664411, -0.22294156]])

In [95]:
Y_Hat=x.dot(Beta_Hat)

In [96]:
Y_Hat

array([[2.61991643, 4.10411394],
       [2.20713105, 4.20082825],
       [1.77789846, 3.67438376],
       [3.2617375 , 4.93406135],
       [2.50374797, 4.23227805],
       [2.57966517, 4.12134767],
       [2.51132953, 3.91413101],
       [2.2147126 , 3.88268121],
       [3.51863286, 5.13976918],
       [1.80522844, 2.79640558]])

In [97]:
x_new=data2[["x0","x1","x2","x3"]].values

In [98]:
x_new

array([[1, 2, 3, 2],
       [1, 1, 2, 3],
       [1, 1, 4, 2]], dtype=int64)

In [99]:
Y_Hat_new=x_new.dot(Beta_Hat)

In [100]:
Y_Hat_new

array([[2.61991643, 4.10411394],
       [2.25496386, 3.86544748],
       [2.40732794, 3.80061102]])

In [102]:
model=MultiOutputRegressor(LinearRegression())

In [103]:
model.fit(x,y)

MultiOutputRegressor(estimator=LinearRegression())

In [104]:
y_pred=model.predict(x_new)

In [105]:
y_pred

array([[2.61991643, 4.10411394],
       [2.25496386, 3.86544748],
       [2.40732794, 3.80061102]])